export const keyShortCutList = [
  { title: "Peragraph", key: "Alt + 0" },
  { title: "Heading 1", key: "Alt + 1" },
  { title: "Heading 2", key: "Alt + 2" },
  { title: "Heading 3", key: "Alt + 3" },
  { title: "Bullet List", key: "Shift + 8" },
  { title: "Number List", key: "Shift + 7" },
  { title: "Check List", key: "Shift + 9" },
  { title: "Block Quote", key: "Shift + B" },
  { title: "Code Block", key: "Alt + C" },
  { title: "Table", key: "Alt + T" },
  { title: "Horizontal Rule", key: "Alt + H" },
  { title: "Bold", key: "B" },
  { title: "Italic", key: "I" },
  { title: "Code", key: "E" },
  { title: "Left align", key: "Shift + L" },
  { title: "Center align", key: "Shift + E" },
  { title: "Right align", key: "Shift + R" },
  { title: "Undo", key: "Z" },
  { title: "Redo", key: "Y" },
  // { title: "", key: "" },
];
